# Generated by Django 3.2.12 on 2023-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('доставки', 'доставки'), ('Yetkazib berish', 'Yetkazib berish')], max_length=200, null=True),
        ),
    ]
